/* AI-assisted portfolio demo. Sample room metadata; no real campus integration. */
const rooms=[{name:'Benson 220',building:'Benson Building',capacity:4,type:'Quiet study',amenities:'Whiteboard · Power outlets'},{name:'Smith 370',building:'Smith Building',capacity:8,type:'Team workspace',amenities:'Display · Whiteboard'},{name:'Romney 260',building:'Romney Building',capacity:12,type:'Collaboration room',amenities:'Display · Power outlets'},{name:'Clark 198',building:'Clark Building',capacity:4,type:'Focus room',amenities:'Whiteboard · Quiet zone'},{name:'STC 340',building:'Science & Technology',capacity:8,type:'Project room',amenities:'Display · Whiteboard'},{name:'Spori 450',building:'Spori Building',capacity:6,type:'Creative workspace',amenities:'Whiteboard · Power outlets'}];
const $=id=>document.getElementById(id);let bookings=[],timer,busy=false,connected=false;const today=new Date();const localDay=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
async function api(path,data){let response;try{response=await fetch(path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined});}catch{throw Error('Cannot reach the Python server. Start server.py and try again.');}const result=await response.json();if(!response.ok)throw Error(result.error||'Request failed.');return result;}
async function read(){try{bookings=await api('/api/bookings');connected=true;document.querySelector('.demo-badge').textContent='SQLITE CONNECTED';}catch(error){connected=false;document.querySelector('.demo-badge').textContent='SERVER OFFLINE';notify(error.message);}render();}
function notify(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(timer);timer=setTimeout(()=>$('toast').hidden=true,5000);}
function conflict(room,day,start,end){return bookings.some(b=>b.room===room&&b.day===day&&b.start<end&&b.end>start);}
function valid(day,start,end){return /^\d{4}-\d{2}-\d{2}$/.test(day)&&/^\d{2}:\d{2}$/.test(start)&&/^\d{2}:\d{2}$/.test(end)&&start<end;}
function node(tag,text,cls){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el;}
function render(){const day=$('filter-date').value,start=$('filter-start').value,end=$('filter-end').value,ok=valid(day,start,end);$('filter-error').textContent=ok?'':'Choose a date and an end time after the start time.';$('rooms').replaceChildren();let available=0;rooms.forEach((room,index)=>{const free=connected&&ok&&!conflict(room.name,day,start,end);if(free)available++;if(room.capacity<Number($('capacity').value)||!(room.name+' '+room.building).toLowerCase().includes($('search').value.trim().toLowerCase()))return;const card=node('article',undefined,'room-card'),art=node('div',undefined,'room-art tone-'+index%3);art.append(node('span',room.building.toUpperCase(),'building'),node('span',free?'● Available':'◷ Unavailable','availability'+(free?'':' busy')));const info=node('div',undefined,'room-info');info.append(node('h3',room.name),node('p',`${room.type} · Up to ${room.capacity} people`),node('div',room.amenities,'amenities'));const button=node('button',free?'Reserve this room ↗':'Choose another time');button.disabled=!free||busy;button.onclick=()=>openBooking(room.name);info.append(button);card.append(art,info);$('rooms').append(card);});if(!$('rooms').children.length)$('rooms').append(node('p','No rooms match. Try a different search or group size.','empty'));$('available-count').textContent=ok?available:'—';$('booking-count').textContent=bookings.length;renderBookings();}
function renderBookings(){$('booking-list').replaceChildren();if(!bookings.length){$('booking-list').append(node('p','No reservations yet. Find a space and book your first session.','empty'));return;}[...bookings].sort((a,b)=>(a.day+a.start).localeCompare(b.day+b.start)).forEach(b=>{const row=node('article',undefined,'booking-row'),details=node('div');details.append(node('h3',b.room),node('p',`${b.day} · ${b.start}–${b.end}`),node('p','Reserved for '+b.owner));const cancel=node('button','Cancel');cancel.onclick=async()=>{if(busy)return;if(cancel.dataset.confirmed){busy=true;cancel.disabled=true;try{await api('/api/cancel',{id:b.id,owner:b.owner});await read();notify('Reservation cancelled.');}catch(error){notify(error.message);}finally{busy=false;render();}}else{cancel.dataset.confirmed='true';cancel.textContent='Confirm cancellation';const keep=node('button','Keep reservation');keep.onclick=renderBookings;row.append(keep);}};row.append(details,cancel);$('booking-list').append(row);});}
function openBooking(room){if(busy)return;$('book-room').value=room||rooms[0].name;$('book-date').value=$('filter-date').value;$('book-start').value=$('filter-start').value;$('book-end').value=$('filter-end').value;$('book-error').textContent='';$('booking-dialog').showModal();}
rooms.forEach(r=>{const option=node('option',r.name);option.value=r.name;$('book-room').append(option);});$('filter-date').value=localDay(today);read();render();$('filters').onsubmit=e=>e.preventDefault();$('filters').oninput=render;$('new-booking').onclick=()=>openBooking();document.querySelector('.close').onclick=()=>$('booking-dialog').close();
$('booking-form').onsubmit=async e=>{e.preventDefault();if(busy)return;const b={room:$('book-room').value,owner:$('book-owner').value.trim(),day:$('book-date').value,start:$('book-start').value,end:$('book-end').value};if(!b.owner||!valid(b.day,b.start,b.end)){$('book-error').textContent='Enter your name and a valid start and end time.';return;}busy=true;const submit=$('booking-form').querySelector('[type="submit"]');submit.disabled=true;try{await api('/api/bookings',b);$('booking-dialog').close();await read();notify('Reservation saved in SQLite.');}catch(error){$('book-error').textContent=error.message;}finally{busy=false;submit.disabled=false;render();}};
document.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>{const show=button.dataset.view==='spaces';$('spaces-view').hidden=!show;$('bookings-view').hidden=show;document.querySelector('.hero').hidden=!show;$('page-title').textContent=show?'Find your focus.':'Your space, reserved.';$('page-subtitle').textContent=show?'Good work starts with the right room. Let’s find yours.':'Keep your upcoming sessions in one place.';$('breadcrumb').textContent=show?'Find a space':'Reservations';document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b===button));});window.addEventListener('focus',()=>{if(!busy)read();});

