const $=id=>document.getElementById(id),key='project-desk-demo-v1';
let records=[],editing=null,user=null,cloud=null,busy=false,epoch=0;
const samples=[{id:'sample1',title:'Campus room reservations',description:'A place for focused work. Explore room availability, booking validation, and a clearer reservation experience.'},{id:'sample2',title:'Networking home lab',description:'Document VLAN configuration, switch management, connectivity checks, and lessons learned.'},{id:'sample3',title:'My next project',description:'Start small. Describe a problem, build a first version, and write down what you learn.'}];
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
function message(s){$('status').textContent=s;}
function readDemo(){try{const raw=localStorage.getItem(key);const data=raw===null?samples:JSON.parse(raw);if(!Array.isArray(data))throw Error();records=data.filter(x=>x&&typeof x.id==='string'&&typeof x.title==='string'&&typeof x.description==='string');message('Local demo · sample ideas and your saved projects.');}catch{records=[];message('Saved demo data could not be read. New saves will replace it.');}}
function lock(value){busy=value;['new','save','login','logout','close'].forEach(id=>$(id).disabled=value);document.querySelectorAll('.actions button').forEach(b=>b.disabled=value);}
function render(){$('count').textContent=records.length;$('projects').replaceChildren();const query=$('search').value.toLowerCase().trim(),shown=records.filter(r=>(r.title+' '+r.description).toLowerCase().includes(query)).sort((a,b)=>a.title.localeCompare(b.title)*($('sort').value==='az'?1:-1));if(!shown.length)$('projects').append(el('p',query?'No matching projects. Try a different search.':'A fresh page. Add your first project to get started.','empty'));shown.forEach(r=>{const card=el('article',undefined,'card');card.append(el('span','✳','icon'),el('h3',r.title),el('p',r.description));const actions=el('div',undefined,'actions'),edit=el('button','Edit project ↗'),remove=el('button','Delete','danger');edit.onclick=()=>open(r);remove.onclick=()=>{if(busy)return;actions.replaceChildren();const yes=el('button','Confirm delete','danger'),no=el('button','Keep project');yes.onclick=()=>write('delete',r.id);no.onclick=render;actions.append(yes,no);};actions.append(edit,remove);card.append(actions);$('projects').append(card);});}
function open(r){if(busy)return;editing=r?.id||null;$('form').reset();$('title').value=r?.title||'';$('description').value=r?.description||'';$('heading').textContent=r?'Edit project':'New project';$('error').textContent='';$('editor').showModal();$('title').focus();}
async function write(action,id,data){if(busy)return;lock(true);const version=epoch,uid=user?.uid;try{if(uid){await cloud.write(action,uid,id,data);if(epoch!==version)return;const loaded=await cloud.load(uid);if(epoch!==version)return;records=loaded;}else{let next=records.map(x=>({...x}));if(action==='delete')next=next.filter(x=>x.id!==id);else if(id)next=next.map(x=>x.id===id?{...x,...data}:x);else next.push({id:crypto.randomUUID(),...data});localStorage.setItem(key,JSON.stringify(next));records=next;}if(epoch!==version)return;$('editor').close();render();message(action==='delete'?'Project deleted.':'Project saved.');}catch{const msg='Could not save this change. Check storage, your connection, and Firebase rules.';$('error').textContent=msg;message(msg);}finally{lock(false);}}
$('new').onclick=()=>open();$('close').onclick=()=>$('editor').close();$('editor').addEventListener('cancel',e=>{if(busy)e.preventDefault();});$('search').oninput=render;$('sort').onchange=render;
$('form').onsubmit=e=>{e.preventDefault();const data={title:$('title').value.trim(),description:$('description').value.trim()};if(!data.title||!data.description){$('error').textContent='Enter a project name and description.';return;}write('save',editing,data);};
$('login').onclick=async()=>{lock(true);try{if(!cloud){const {firebaseConfig}=await import('./config.js');const appSDK=await import('https://www.gstatic.com/firebasejs/10.8.1/firebase-app.js'),authSDK=await import('https://www.gstatic.com/firebasejs/10.8.1/firebase-auth.js'),fs=await import('https://www.gstatic.com/firebasejs/10.8.1/firebase-firestore.js');const app=appSDK.initializeApp(firebaseConfig),auth=authSDK.getAuth(app),db=fs.getFirestore(app);cloud={login:()=>authSDK.signInWithPopup(auth,new authSDK.GoogleAuthProvider()),logout:()=>authSDK.signOut(auth),load:async uid=>(await fs.getDocs(fs.collection(db,'users',uid,'projects'))).docs.map(d=>({...d.data(),id:d.id})),write:(action,uid,id,data)=>action==='delete'?fs.deleteDoc(fs.doc(db,'users',uid,'projects',id)):id?fs.updateDoc(fs.doc(db,'users',uid,'projects',id),data):fs.addDoc(fs.collection(db,'users',uid,'projects'),data)};authSDK.onAuthStateChanged(auth,async next=>{const version=++epoch;user=next;records=[];$('editor').close();$('mode').textContent=next?'FIREBASE CLOUD':'LOCAL DEMO';$('login').hidden=!!next;$('logout').hidden=!next;$('account').textContent=next?'Your private Firebase project library.':'Demo projects stay in this browser. Cloud records are separate.';render();if(next){message('Loading your cloud projects…');try{const loaded=await cloud.load(next.uid);if(epoch===version){records=loaded;render();message('Cloud projects loaded.');}}catch{if(epoch===version)message('Could not load cloud projects. Check your connection and rules.');}}else{readDemo();render();}});}await cloud.login();}catch{message('Firebase connection unavailable. Follow FIREBASE.md to add config.js and enable Google sign-in. Your local demo is still available.');}finally{lock(false);}};
$('logout').onclick=async()=>{lock(true);try{await cloud.logout();}catch{message('Sign-out failed. Try again.');}finally{lock(false);}};
window.addEventListener('storage',e=>{if(e.key===key&&!user&&!busy){readDemo();render();}});readDemo();render();

