/* AI-assisted portfolio demo. Sample room metadata; no real campus integration. */
const rooms=[{name:'Benson 220',building:'Benson Building',capacity:4,type:'Quiet study',amenities:'Whiteboard · Power outlets'},{name:'Smith 370',building:'Smith Building',capacity:8,type:'Team workspace',amenities:'Display · Whiteboard'},{name:'Romney 260',building:'Romney Building',capacity:12,type:'Collaboration room',amenities:'Display · Power outlets'},{name:'Clark 198',building:'Clark Building',capacity:4,type:'Focus room',amenities:'Whiteboard · Quiet zone'},{name:'STC 340',building:'Science & Technology',capacity:8,type:'Project room',amenities:'Display · Whiteboard'},{name:'Spori 450',building:'Spori Building',capacity:6,type:'Creative workspace',amenities:'Whiteboard · Power outlets'}];
const $=id=>document.getElementById(id),key='roomly-reservations-v1';let bookings=[],timer;const today=new Date();const localDay=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function read(){try{const data=JSON.parse(localStorage.getItem(key)||'[]');if(!Array.isArray(data))throw Error();bookings=data.filter(b=>b&&typeof b.id==='string'&&rooms.some(r=>r.name===b.room)&&typeof b.owner==='string'&&typeof b.day==='string'&&typeof b.start==='string'&&typeof b.end==='string');}catch{bookings=[];notify('Saved data could not be read. New bookings will replace it.');}}
function notify(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(timer);timer=setTimeout(()=>$('toast').hidden=true,5000);}
function persist(next){try{localStorage.setItem(key,JSON.stringify(next));bookings=next;return true;}catch{notify('Storage is unavailable. Your changes were not saved.');return false;}}
function conflict(room,day,start,end){return bookings.some(b=>b.room===room&&b.day===day&&b.start<end&&b.end>start);}
function valid(day,start,end){return /^\d{4}-\d{2}-\d{2}$/.test(day)&&/^\d{2}:\d{2}$/.test(start)&&/^\d{2}:\d{2}$/.test(end)&&start<end;}
function node(tag,text,cls){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el;}
function render(){const day=$('filter-date').value,start=$('filter-start').value,end=$('filter-end').value,ok=valid(day,start,end);$('filter-error').textContent=ok?'':'Choose a date and an end time after the start time.';$('rooms').replaceChildren();let available=0;rooms.forEach((room,index)=>{const free=ok&&!conflict(room.name,day,start,end);if(free)available++;if(room.capacity<Number($('capacity').value)||!(room.name+' '+room.building).toLowerCase().includes($('search').value.trim().toLowerCase()))return;const card=node('article',undefined,'room-card'),art=node('div',undefined,'room-art tone-'+index%3);art.append(node('span',room.building.toUpperCase(),'building'),node('span',free?'● Available':'◷ Unavailable','availability'+(free?'':' busy')));const info=node('div',undefined,'room-info');info.append(node('h3',room.name),node('p',`${room.type} · Up to ${room.capacity} people`),node('div',room.amenities,'amenities'));const button=node('button',free?'Reserve this room ↗':'Choose another time');button.disabled=!free;button.onclick=()=>openBooking(room.name);info.append(button);card.append(art,info);$('rooms').append(card);});if(!$('rooms').children.length)$('rooms').append(node('p','No rooms match. Try a different search or group size.','empty'));$('available-count').textContent=ok?available:'—';$('booking-count').textContent=bookings.length;renderBookings();}
function renderBookings(){$('booking-list').replaceChildren();if(!bookings.length){$('booking-list').append(node('p','No reservations yet. Find a space and book your first session.','empty'));return;}[...bookings].sort((a,b)=>(a.day+a.start).localeCompare(b.day+b.start)).forEach(b=>{const row=node('article',undefined,'booking-row'),details=node('div');details.append(node('h3',b.room),node('p',`${b.day} · ${b.start}–${b.end}`),node('p','Reserved for '+b.owner));const cancel=node('button','Cancel');cancel.onclick=()=>{if(cancel.dataset.confirmed){read();if(persist(bookings.filter(x=>x.id!==b.id))){render();notify('Reservation cancelled.');}}else{cancel.dataset.confirmed='true';cancel.textContent='Confirm cancellation';const keep=node('button','Keep reservation');keep.onclick=renderBookings;row.append(keep);}};row.append(details,cancel);$('booking-list').append(row);});}
function openBooking(room){$('book-room').value=room||rooms[0].name;$('book-date').value=$('filter-date').value;$('book-start').value=$('filter-start').value;$('book-end').value=$('filter-end').value;$('book-error').textContent='';$('booking-dialog').showModal();}
rooms.forEach(r=>{const option=node('option',r.name);option.value=r.name;$('book-room').append(option);});$('filter-date').value=localDay(today);read();render();$('filters').onsubmit=e=>e.preventDefault();$('filters').oninput=render;$('new-booking').onclick=()=>openBooking();document.querySelector('.close').onclick=()=>$('booking-dialog').close();
$('booking-form').onsubmit=e=>{e.preventDefault();read();const b={id:crypto.randomUUID(),room:$('book-room').value,owner:$('book-owner').value.trim(),day:$('book-date').value,start:$('book-start').value,end:$('book-end').value};if(!b.owner||!valid(b.day,b.start,b.end)){$('book-error').textContent='Enter your name and a valid start and end time.';return;}if(conflict(b.room,b.day,b.start,b.end)){$('book-error').textContent='That room is already booked during this time. Try another room or time slot.';return;}if(persist([...bookings,b])){$('booking-dialog').close();render();notify(`${b.room} reserved for ${b.start}–${b.end}.`);}};
document.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>{const show=button.dataset.view==='spaces';$('spaces-view').hidden=!show;$('bookings-view').hidden=show;document.querySelector('.hero').hidden=!show;$('page-title').textContent=show?'Find your focus.':'Your space, reserved.';$('page-subtitle').textContent=show?'Good work starts with the right room. Let’s find yours.':'Keep your upcoming sessions in one place.';$('breadcrumb').textContent=show?'Find a space':'Reservations';document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b===button));});window.addEventListener('storage',()=>{read();render();});

